---
language: python
python: 3.8.2

services:
  - docker

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  - pip install -r requirements.txt
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - molecule test
