---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: ../../.venv/bin/python
      stdout_callback: yaml
verifier:
  name: ansible
